# Tema 2

Topics:
1. Metoda substitutiei inverse
2. Algoritmul de Elminiare Gauss

In [80]:
import numpy as np
import unittest
import random
import seaborn as sns
import matplotlib.pylab as plt

np.random.seed(10)

np.set_printoptions(suppress=True)
#np.set_printoptions(precision=7)

## 1. Metoda substitutiei inverse

**TL;DR:** Metoda substituiei inverse rezolva sisteme linare in care matricea asociata sistemului este triunghiulara (inferior sau superior).

* **Ce este o matrice triunghiulara superior?** O matrice triunghiulara superior este o matrice care are valori nule sub diagonala principala. 

In [81]:
# generate a 4x4 matrix with elements from 1 to 16
A = (np.arange(4*4) + 1).reshape(4, 4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [82]:
# generated superior triangular matrix from A
np.triu(A)

array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0,  0, 16]])

* **Ce este o matrice triunghiulara inferior?** O matrice triunghiulara inferior este o matrice care are valori nule deasupra diagonala principala. 

In [83]:
# generated inferior triangular matrix from A
np.tril(A)

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

### Metoda substitutiei inverse
Fie sistemul liniar:
$$
A x=b
$$

unde matricea sistemului $A$ este **triunghiulară superior**. Pentru a găsi soluţia unică a sistemului, trebuie ca matricea să fie nesingulară. Determinantul matricelor triunghiulare este dat de formula:
$$
\operatorname{det} A=a_{11} a_{22} \cdots a_{n n}
$$
Prin urmare, pentru rezolvarea sistemului vom presupune că:
$$
\operatorname{det} A \neq 0 \Longleftrightarrow a_{i i} \neq 0 \quad \forall i=1,2, \ldots, n
$$
Vom considera sistemul liniar cu matrice superior triunghiulară:

\begin{align*}
a_{11} x_{1}+\cdots+a_{1 i} x_{i}+\cdots+a_{1 n-1} x_{n-1}+a_{1 n} x_{n}&=b_{1}\\
\cdots\\
a_{i i} x_{i}+\cdots+a_{i n-1} x_{n-1}+a_{i n} x_{n}&=b_{i}\\
\cdots\\
a_{n-1 n-1} x_{n-1}+a_{n-1 n} x_{n}&=b_{n-1}\\
a_{n n} x_{n}&=b_{n}\\
\end{align*}

Necunoscutele $x_{1}, x_{2}, \ldots, x_{n}$ se deduc pe rând, folosind ecuaţiile sistemului de la ultima către prima. Din ultima ecuaţie, deducem valoarea lui $x_{n}$ :
$$
x_{n}=\frac{b_{n}}{a_{n n}}
$$
Folosind valoarea lui $x_{n}$ calculată mai sus, din penultima ecuaţie obţinem:
$$
x_{n-1}=\frac{b_{n-1}-a_{n-1 n} x_{n}}{a_{n-1 n-1}}
$$


Continuăm să calculăm valori $x_{i}$ din ecuaţiile sistemului:
$$
x_{i}=\frac{b_{i}-a_{i i+1} x_{i+1}-\cdots-a_{i n} x_{n}}{a_{i i}}
$$
Din prima ecuaţie găsim valoarea lui $x_{1}$ :
$$
x_{1}=\frac{b_{1}-a_{12} x_{2}-\cdots-a_{1 n} x_{n}}{a_{11}}
$$
Procedeul descris mai sus poartă numele de metoda substituţiei inverse pentru rezolvarea sistemelor liniare cu matrice superior triunghiulară:
$$
x_{i}=\frac{\left(b_{i}-\sum_{j=i+1}^{n} a_{i j} x_{j}\right)}{a_{i i}} \quad, \quad i=n, n-1, \ldots, 2,1
$$

#### Exemplu pentru metoda substitutiei inverse
$$
\left(\begin{array}{ccc}
3 & 1 & -5 \\
& -2 & 4 \\
& & 2
\end{array}\right)\left(\begin{array}{l}
x_{1} \\
x_{2} \\
x_{3}
\end{array}\right)=\left(\begin{array}{c}
1 \\
10 \\
6
\end{array}\right)$$

#### Rezolvare:

$$x_n = \frac{b_n}{a_{nn}} \Rightarrow x_3 = \frac{b_3}{a_{33}} = \frac{6}{2} = 3$$


$$
x_{i}=\frac{\left(b_{i}-\sum_{j=i+1}^{n} a_{i j} x_{j}\right)}{a_{i i}} \quad, \quad i=n, n-1, \ldots, 2,1
\Rightarrow
x_2=\frac{10 - (4 * 3)}{-2}=1
$$

$$
x_1=\frac{1 - ((1 * 1) + (-5 * 3))}{3} = \frac{1 - (-14)}{3} = \frac{15}{3} = 5
$$

In [84]:
# Generate random superior triangular system
n = 10
A = np.random.randint(low=1, high=100, size=n*n).reshape(n, n)
A = np.triu(A)
b = np.random.randint(low=1, high=100, size=n)

A, b

(array([[10, 16, 65, 29, 90, 94, 30,  9, 74,  1],
        [ 0, 37, 17, 12, 55, 89, 63, 34, 73, 79],
        [ 0,  0, 55, 78, 70, 14, 26, 14, 93, 87],
        [ 0,  0,  0, 13, 66, 32, 58, 37, 28, 19],
        [ 0,  0,  0,  0, 95, 12, 29, 75, 89, 10],
        [ 0,  0,  0,  0,  0, 12, 18, 47,  8, 76],
        [ 0,  0,  0,  0,  0,  0,  6,  5, 72, 89],
        [ 0,  0,  0,  0,  0,  0,  0, 16,  7, 86],
        [ 0,  0,  0,  0,  0,  0,  0,  0, 43, 58],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 24]]),
 array([ 4, 30, 17, 85, 83, 15, 52, 80, 18, 51]))

In [85]:
def substitution_method(A, b, n):
  det_A = 1
  for i in range(0, n):
      det_A *= A[i][i]

  if det_A != 0:
    x = np.zeros(n)
    for i in reversed(range(n)):
      x[i] = b[i]
      sum = 0
      for j in range(i + 1, n):
        sum = sum + A[i][j] * x[j]
      x[i] -= sum
      x[i] /= A[i][i]

  else:

     raise Exception("Matrice singulara")

  return x

In [86]:
# Apply substitution method
x = substitution_method(A, b, n)
x

array([-138.82179682,  -12.53522996,   40.25857887,  -33.34281161,
          4.58517824,   -6.08406008,   10.97710756,   -5.35101744,
         -2.44767442,    2.125     ])

In [87]:
# Compute norm between the matrix multiplication of A and our solution
diff = A @ x - b
diff

array([ 0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.])

In [88]:
# Test if the matrix is singular
A[2, 2] = 0

try: 
    x = substitution_method(A, b, n)
except Exception as e: 
    print(e)

Matrice singulara


### 2. Algoritmul de eliminare Gauss


Ideea de rezolvare este de a transforma succesiv sistemul folosind operaţii elementare (ce nu modifică soluţia sistemului) şi a aduce matricea $A$ la o formă superior triunghiulară . Algoritmul se desfăşoară în $(n-1)$ paşi. La un pas $l$ oarecare se transformă coloana $l$ a matricei $A$ în formă superior triunghiulară fără a modifica forma triunghiulară a primelor $(l-1)$ coloane.


**Pas $l$ :** Presupunem că elementul de pe poziţia $(l, l)$ numit şi element pivot este nenul, $a_{l l} \neq 0$. Pentru $i=l+1, \ldots, n$ se înmulteste linia $l$ a matricei $A$ $\mathrm{cu}\left(-a_{i l} / a_{l l}\right)$ şi se adună la linia $i$. Schimbare se face şi asupra componentei $i$ a vectorului $b$. Matricea $A$ şi vectorul $b$ se modifică astfel:
$$
\begin{aligned}
&a_{i j}^{\prime}=a_{i j}-\frac{a_{i l}}{a_{l l}} a_{l j} \quad, \quad i=\overline{l+1, n}, j=\overline{l+1, n}  &(5)\\
&b_{i}^{\prime}=b_{i}-\frac{a_{i l}}{a_{l l}} b_{l} \quad, \quad i=\overline{l+1, n}  &(6)\\
&a_{i l}^{\prime}=0 \quad, \quad i=\overline{l+1, n}, &(7)\\
&a_{i j}^{\prime}=a_{i j} \quad, \quad b_{i}^{\prime}=b_{i} \text { pentru restul indicilor } i, j
\end{aligned}
$$

In formula $(5)$ factorul $f=\frac{a_{i l}}{a_{l l}}$ se calculează în afara buclei for pentru $j$.

In [89]:
def pivot(A, b, l, n):
  i0 = 0
  max = 0
  for i in range(l, n):
    if abs(A[i][l]) > max:
      max = abs(A[i][l])
      i0 = i
  A[i0], A[l] = A[l], A[i0]
  b[i0], b[l] = b[l], b[i0]

  return A, b

In [90]:
# def gauss_algorithm(A, b, n):
#   evo = []

#   for l in range(n):
#     evo.append(np.copy(A))
#     A, b = pivot(A, b, l, n)
    
#     A_new = np.copy(A)
#     b_new = np.copy(b)
#     for i in range(l + 1, n):
#       if abs(A[l][l]) == 0:
#         print("Pivot Invalid")
#         print(evo)
#         return None, None, None
        
#       f = A[i][l] / A[l][l]
#       for j in range(l + 1, n):
#         A_new[i][j] -= f * A[l][j]
#       b[i] -= f * b[l]
#       A_new[i][l] = 0

#     A, b = A_new, b_new

#   return A, b, evo

def gauss_algorithm(A, b, n):
    evo = []
    A_copy = np.matrix.copy(A)
    A_copy = A_copy.astype('float64')

    B_copy = np.copy(b)
    B_copy = B_copy.astype('float64')
    evo.append(np.concatenate((A_copy, B_copy[:,None]),axis=1))
    # evo.append((A_copy)
    
    for l in range(n - 1):
      if A_copy[l][l] == 0.0:
          print("Zero")
          A_copy = pivot(A_copy, B_copy, l, n)
      for i in range(l + 1, n):
          f = A_copy[i][l] / A_copy[l][l]

          B_copy[i] = B_copy[i] - f * B_copy[l]

          for j in range(l + 1, n):
            A_copy[i][j] = A_copy[i][j] - f * A_copy[l][j]

          A_copy[i][l] = 0
          evo.append(np.concatenate((A_copy, B_copy[:,None]),axis=1))
          # evo.append((A_copy)

    #print(type(A_copy[1][1]), type(A_copy))

    return A_copy, B_copy, evo

#### Alegerea pivotului $a_{l l} \neq 0\left(\left|a_{l l}\right|>\epsilon\right)$

Pentru a aduce pe poziţia $(l, l)$ un element nenul avem trei posibilităti:
1. **Varianta fără pivotare** : Se alege primul indice $i_{0} \in\{l, l+1, \cdots, n\}$ astfel ca $a_{i_{0} l} \neq 0$. Se interschimbă liniile $i_{0}$ şi $l$ ale matricei $A$ şi componentele $i_{0}$ şi $l$ ale vectorului $b$.
2. **Varianta cu pivotare parțială**: 
Se alege indicele $i_{0} \in\{l, l+1, \cdots, n\}$ astfel ca:
$$
\left|a_{i_{0} l}\right|=\max \left\{\left|a_{i l}\right|, i=\overline{l, n}\right\} .
$$
Se interschimbă liniile $i_{0}$ şi $l$ ale matricei $A$ şi componentele $i_{0}$ şi $l$ ale vectorului $b$.
3. **Varianta cu pivotare totală** 
Se aleg indicii $i_{0}, j_{0} \in\{l, l+1, \cdots, n\}$ astfel ca:
$$
\left|a_{i_{0} j_{0}}\right|=\max \left\{\left|a_{i j}\right|, i=\overline{l, n}, j=\overline{l, n}\right\} .
$$
Se interschimbă liniile $i_{0}$ şi $l$, coloanele $j_{0}$ şi $l$ ale matricei $A$ şi componentele $i_{0}$ şi $l$ ale vectorului $b$.
Dacă după efectuarea pivotării (indiferent de varianta de pivotare aleasă) elementul pivot este nul
$$
a_{l l}=0 \quad \sim \quad \operatorname{abs}(a[l, l]) \leq \epsilon
$$
atunci matricea $A$ este singulară.

**Observaţii:**
1. In pasul Gauss $l$ $(5)+(6)+(7)$ calculele se pot efectua în matricea $A$ iniţială $\left(a^{\prime}=a\right)$.

2. Dacă pentru memorarea matricei $A$ şi a vectorului $b$ se foloseşte o matrice cu $n$ linii şi $(n+1)$ coloane, vectorul $b$ fiind memorat în coloana $(n+1)$ a matricei $A$, calculele $(6)$ sunt incluse în $(5)$ pentru $j=n+1$; se simplifică şi interschimbarea liniilor $i_{0}$ şi $l$.

3. Dacă pivotul se alege folosind varianta a 3-a, cu pivotare totală, la final trebuie să avem grijă sa restabilim ordinea iniţială a componentelor vectorului soluţie (ţinând cont de coloana $j_{0}$ a pivotului de la fiecare pas).

#### Exemplu pentru algoritmul de eliminare Gauss

Youtube: https://www.youtube.com/watch?v=2j5Ic2V7wq4 - puteti cauta si altele pt "Gaussian elimination"

Exemplul din tema (fara pivotare):
$$
A=\left(\begin{array}{lll}
2 & 0 & 1 \\
0 & 2 & 1 \\
4 & 4 & 6
\end{array}\right) x=\left(\begin{array}{c}
5 \\
1 \\
14
\end{array}\right)
$$

1. **Pasul 1:** Verificam daca $a_{11}$ este nenul. Raspunsul este da, deci $a_{11}$ este un pivot valid. Astfel putem incepe sa facem valorile $a_{21}$ si $a_{31}$ nule.
  * $a_{21}$ este deja nul, deci vom alsa linia $2$ neschimbata
  * $a_{31}$ nu este nul, deci incercam sa facem elementul 0 inmultind linia 3 cu valoarea $(−𝑎_{𝑖𝑙}/𝑎{𝑙𝑙})$ unde $i = 3$, asadar Linia 3 devine $Linia3-2 * Linia 1$
  Asadar
  $$
A=\left(\begin{array}{lll}
2 & 0 & 1 \\
0 & 2 & 1 \\
0 & 4 & 4
\end{array}\right) x=\left(\begin{array}{c}
5 \\
1 \\
4
\end{array}\right)
$$

1. **Pasul 2:** Verificam daca $a_{22}$ este nenul. Raspunsul este da, deci $a_{22}$ este un pivot valid. Astfel putem incepe sa facem valorea $a_{23}$ nula.
  * $a_{23}$ nu este nula, deci incercam sa facem elementul 0 inmultind linia 2 cu -4/2 si adunand la linia 3
  Asadar
  $$
A=\left(\begin{array}{lll}
2 & 0 & 1 \\
0 & 2 & 1 \\
0 & 0 & 2
\end{array}\right) x=\left(\begin{array}{c}
5 \\
1 \\
2
\end{array}\right)
$$

In [91]:
# Generate random superior triangular system
n = 5
A = np.random.randint(low=1, high=100, size=n*n).reshape(n, n)
b = np.random.randint(low=1, high=100, size=n)
#A[1][1] = 0
A, b

(array([[54, 26, 49, 18, 33],
        [82, 81, 42, 91, 13],
        [31, 82, 18, 17,  1],
        [32, 74, 65, 39, 23],
        [97, 67, 68, 63, 96]]), array([28, 83, 63, 78, 49]))

In [92]:
#A, b = (np.array([[54, 26, 49, 18, 33],
 #       [82, 81, 42, 91, 13],
  #      [31, 82, 18, 17,  1],
   #     [32, 74, 65, 39, 23],
    #    [97, 67, 68, 63, 96]]),
 #np.array([28, 83, 63, 78, 49]))

In [93]:
A_gauss, b_gauss, evo = gauss_algorithm(A, b, n)
A_gauss, b_gauss

(array([[ 54.        ,  26.        ,  49.        ,  18.        ,
          33.        ],
        [  0.        ,  41.51851852, -32.40740741,  63.66666667,
         -37.11111111],
        [  0.        ,   0.        ,  42.22524532, -96.1882248 ,
          42.00936664],
        [  0.        ,   0.        ,   0.        , 124.5897918 ,
         -25.46278085],
        [  0.        ,   0.        ,   0.        ,   0.        ,
          56.98119568]]),
 array([ 28.        ,  40.48148148, -18.47279215,  40.0195629 ,
        -19.71017638]))

In [94]:
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

def f(x):
    data_set = evo[x]
    ax = sns.heatmap( data_set , vmin=-150, vmax=150, linewidth = 0 , cmap = 'coolwarm_r' )
      
    plt.title("Matrix evolution at step: " + str(x) )
    plt.show()

def plot_matrix_evolution(evo, label):
  interact(f, x=(0, 10, 1));


In [95]:
plot_matrix_evolution(evo, "Gauss algorithm matrix evolution")

interactive(children=(IntSlider(value=5, description='x', max=10), Output()), _dom_classes=('widget-interact',…

In [96]:
x_gauss = substitution_method(A_gauss, b_gauss, n=n)
x_gauss

array([-0.10174426,  0.65425972,  0.47732772,  0.25051665, -0.34590668])

Fie $x_{\text {Gauss }}$ soluţia aproximativă calculată. Să se verifice soluţia afişând următoarea normă:
$$
\left\|A^{i n i t} x_{G a u s s}-b^{i n i t}\right\|_{2}
$$
$A^{\text {init }}$ şi $b^{\text {init }}$ sunt datele iniţiale, nu cele modificate pe parcursul algoritmului. Am notat cu $\|\cdot\|_{2}$ norma Euclidiană. Această normă ar trebui să fie mai mică decât $10^{-6}$, dacă aţi implementat corect metoda eliminării Gauss.

In [97]:
def my_get_norm(vect, n, p):
    sum = 0
    for i in range(n):
        sum = sum + np.float_power(np.fabs(vect[i]), p)

    return np.float_power(sum, 1 / p)

In [98]:
norm = my_get_norm(A @ x_gauss - b, n, 2)
norm_lib = np.linalg.norm(A @ x_gauss - b)
if norm == norm_lib:
    print("Normele sunt egale")
if norm_lib <= np.float_power(10, -6):
    print("Mai mic ca 10 la -6")
print(norm)
print(norm_lib)

Normele sunt egale
Mai mic ca 10 la -6
2.2469334198890888e-14
2.2469334198890888e-14


Folosindu-se una din bibliotecile menţionate în pagina laboratorului, să se calculeze şi să se afişeze soluţia sistemului $A x=b$ şi inversa matricei $A, x_{b i b l}$ şi $A_{b i b l}^{-1}$. Să se afişeze următoarele norme:
$$
\begin{gathered}
\left\|x_{\text {Gauss }}-x_{\text {bibl }}\right\|_{2} \\
\left\|x_{\text {Gauss }}-A_{\text {bibl }}^{-1} b^{i n i t}\right\|_{2} .
\end{gathered}
$$
Aceste norme ar trebui să fie mai mici decât $10^{-6}$.

In [99]:
def lib_solve(A, b):
    return np.linalg.solve(A, b)

def get_norm(V):

    return np.linalg.norm(V)

def lib_inv(M):
  return np.linalg.inv(M)

In [100]:
x_lib = lib_solve(A, b)
x_lib

array([-0.10174426,  0.65425972,  0.47732772,  0.25051665, -0.34590668])

In [101]:
get_norm(x_gauss - x_lib)

2.4196749845665633e-16

In [102]:
get_norm(x_gauss - lib_inv(A) @ b)

7.535012591929473e-16

### 3. Calculul inversei unei matrice folosind metoda lui Gauss

Dacă se cunoaşte o metodă numerică de rezolvare a sistemelor liniare (în cazul de faţă se va folosi algoritmul de eliminare Gauss), coloanele matricei inverse se pot aproxima rezolvând $n$ sisteme liniare.
Coloana $j$ a matricei $A^{-1}$ se aproximează rezolvând sistemul liniar:
$$
\begin{aligned}
&A x=e_{j}, j=1,2, \ldots, n, \\
&e_{j}=(0, \ldots, 1,0 \ldots, 0)^{T}, 1 \text { este pe poziţia } j \text { în vectorul } e_{j}
\end{aligned}
$$
Procedura de calcul a matricei $A_{\text {Gauss }}^{-1}$ este următoarea:
- Se calculează eliminarea Gauss a matricei extinse $\left[A, I_{n}\right] \in \mathbb{R}^{n \times 2 n}\left(I_{n}\right.$ este matricea unitate de dimensiune $n$ ). Se adaptează varianta a 2-a a algoritmului de eliminare Gauss cu pivotare parţială, astfel încât să modifice toate coloanele matricei $I_{n}$ simultan, împreună cu transformarea matricei $A$ în formă superior triunghiulară. În varianta a 2 -a a algoritmului descrisă mai sus se face transformarea Gauss a matricei $[A, b] \in \mathbb{R}^{n \times(n+1)}$.
La final, matricea va avea următoarea formă $\left[R, I_{\text {transformat }}\right]$ unde $R$ este forma superior triunghiulară a matricei $A$ iar $I_{\text {transformat }}$ este matricea $I_{n}$ modificată conform algoritmului de eliminare Gauss.
- for $j=1, \ldots, n$
  1. $b=$ coloana $j$ a matricei $I_{\text {transformat }}$;
  2. se rezolvă sistemul superior triunghiular $R x=b$, folosind metoda substituţiei inverse, se obţine soluţia $x^{*}\left(x^{*}\right.$ este soluţia sistemului liniar $A x=e_{j}$);
  3. se memorează $x^{*}$ în coloana $j$ a matricei $A_{\text {Gauss }}^{-1}$;

Procedura de mai sus detaliază, în fapt, rezolvarea numerică a ecuaţiei matriceale:

$$A X=I_{n}, X \in \mathbb{R}^{n \times n}, I_{n}=\text { matricea unitate. }$$

In [103]:
def pivot2(A, b, l, n):
  i0 = 0
  max = 0
  for i in range(l, n):
    if abs(A[i][l]) > max:
      max = abs(A[i][l])
      i0 = i

  temp = np.copy(A[i0])
  A[i0] = np.copy(A[l])
  A[l] = temp
  temp = np.copy(b[i0])
  b[i0] = np.copy(b[l])
  b[l] = temp
  #print(A)
  #print(b)
  #print("Done")

  return A, b

In [104]:
def gauss_algorithm(A, b, n):
    evo = []
    A_copy = np.matrix.copy(A)
    A_copy = A_copy.astype('float64')

    B_copy = np.copy(b)
    B_copy = B_copy.astype('float64')
    #evo.append(np.concatenate((A_copy, B_copy[:,None]),axis=1))
    # evo.append((A_copy)

    for l in range(n - 1):
      #if A_copy[l][l] == 0.0:
          #print("Zero")
      A_copy, B_copy = pivot2(A_copy, B_copy, l, n)

      for i in range(l + 1, n):
          f = A_copy[i][l] / A_copy[l][l]

          # B_copy[i] = B_copy[i] - f * B_copy[l]

          for j in range(l + 1, n):
            A_copy[i][j] = A_copy[i][j] - f * A_copy[l][j]
            B_copy[i][j] = B_copy[i][j] - f * B_copy[l][j]

          A_copy[i][l] = 0
          #evo.append(np.concatenate((A_copy, B_copy[:,None]),axis=1))
          # evo.append((A_copy)

    #print(type(A_copy[1][1]), type(A_copy))

    return A_copy, B_copy, evo

In [105]:
def get_inv(A):
  n = len(A)
  In = np.identity(n)
  R, It, evo = gauss_algorithm(A, In, n)
  sol=[]
  #print(R)
  #print(It)
  inv = np.empty(shape=(n, n))
  inv.fill(0)

  for i in range(n):
      # iau coloana corespunzatoare iteratiei din It
      b = np.array([It[j][i] for j in range(n)])
      #print(R, b)
      x = substitution_method(R, b, n)

      #pun in coloana i din inversa vectorul solutie
      for z in range(n):
          inv[z][i] = x[z]

  # print(inv)


  return inv

In [106]:
#A = np.array([[2, 0.5, 2], [4, 3, 8], [0, 2, 6]])
my_inv = get_inv(A)
my_inv @ A

array([[-0.14430167, -1.22212334, -0.77559804, -1.30953316, -0.25826463],
       [ 0.37422588,  1.37302318,  0.25528887,  0.43833446,  0.08773039],
       [-0.7411154 , -0.86092147,  0.50195326, -0.82190083, -0.15875454],
       [ 1.02221992,  1.29775449,  0.68016231,  2.09196994,  0.20544339],
       [ 0.74916792,  0.73268268,  0.51193341,  0.88282768,  1.17735529]])

Folosind algoritmul de eliminare Gauss, calculaţi o aproximare a inversei acestei matrice, $A_{\text {Gauss }}^{-1}$. Să se afişeze:
$$
\left\|A_{\text {Gauss }}^{-1}-A_{\text {bibl }}^{-1}\right\|
$$
Folosiţi orice normă matriceală este implementată în bibliotecă.

In [107]:
print(lib_inv(A))
#print(lib_inv(A) @ A)
get_norm(lib_inv(A) - my_inv)

[[ 0.02624596  0.00535478  0.00898991 -0.02060418 -0.0049044 ]
 [-0.00897094 -0.00391305  0.0145223   0.00219841  0.00293568]
 [ 0.01598906 -0.0021614  -0.01117361  0.01754046 -0.00928956]
 [-0.02044983  0.01192665 -0.01572998  0.00831335  0.00358667]
 [-0.01816377 -0.00897544 -0.00098147  0.00140437  0.01754965]]


0.022182924733992866

**Bonus (25pt)**: Să se adapteze algoritmul de eliminare Gauss cu pivotare parţială pentru matrice tridiagonale de forma:
$$
A=\left(\begin{array}{cccccccc}
a_{1} & b_{1} & 0 & 0 & \cdots & 0 & 0 & 0 \\
c_{1} & a_{2} & b_{2} & 0 & \cdots & 0 & 0 & 0 \\
0 & c_{2} & a_{3} & b_{3} & \cdots & 0 & 0 & 0 \\
\vdots & & & & & & & \\
0 & 0 & 0 & 0 & \cdots & c_{n-2} & a_{n-1} & b_{n-1} \\
0 & 0 & 0 & 0 & \cdots & 0 & c_{n-1} & a_{n}
\end{array}\right)
$$
Să se calculeze soluţia sistemului $A x=g$. La sfârşitul rulării algoritmului de eliminare Gauss pentru matrice tridiagonală, se ajunge la o matrice de forma:
$$
R=\left(\begin{array}{cccccccc}
d_{1} & e_{1} & f_{1} & 0 & \cdots & 0 & 0 & 0 \\
0 & d_{2} & e_{2} & f_{2} & \cdots & 0 & 0 & 0 \\
\vdots & & & & & & & \\
0 & 0 & 0 & 0 & \cdots & d_{n-2} & e_{n-2} & f_{n-2} \\
0 & 0 & 0 & 0 & \cdots & 0 & d_{n-1} & e_{n-1} \\
0 & 0 & 0 & 0 & \cdots & 0 & 0 & d_{n}
\end{array}\right)
$$
La aplicarea algoritmului de eliminare Gauss, să se lucreze doar cu cei 6 vectori $a, b, c, d, e, f$.

https://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm


In [136]:
def pivot(a, b, c, f, v, l, n):
  if c[l] > a[l]:
    a[l], c[l] = c[l], a[l]
    b[l], a[l+1] = a[l+1], b[l]
    if l < n-2:
      f[l], b[l+1] = b[l+1], 0
    v[l], v[l+1] = v[l+1], v[l]


In [137]:
# To be completed by the brave ones

def TriDiagonal_Matrix_Algorithm(n,a,b,c,v):
  l=0
  f = np.zeros(n)
  pivot(a, b, c, f, v, l, n)
  while l<=n-3 and abs(a[l]) > pow(10,-5):
    
    ff = c[l] / a[l]
    for i in range(l + 1, n):
      v[i] = v[i] - ff * v[l]

    if l<n-2:
      a[l+1] = a[l+1] - ff * b[l]
      c[l+1] = c[l+1] -ff * b[l]

    if l<n-3:
      c[l+2] = c[l+2] -ff * b[l]
    if l<n-2:
      b[l+1] = b[l+1] - ff * f[l]
      a[l+2] = a[l+2] -ff * f[l]

    c[l] = 0
    l+=1
    pivot(a, b, c, f, v, l, n)

  d=a
  e=b
  return d, e, f

In [115]:
n=3
a=[2.04]*3
b=[-1]*2
c=[-1]*2
v=[48.8,0.8,0.8]
#2.04 1.5498 1.3948
#-1 -1
#0 uri

In [135]:
TriDiagonal_Matrix_Algorithm(n,a,b,c,v)

([2.04, 0.07921568627450976, -110.08871287128719],
 [-1, -1.0],
 array([0., 0., 0.]))